language: node_js
node_js:
  - "4.1"
cache:
  directories:
    - node_modules
branches:
  only:
  - 'stable'
after_success:
  - ls -la
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
